### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by dtransposed** [stared/xbar-rescuetime-activities#1]
Followed the README.md and I end up here:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/c5d7c6ef-cffe-40ad-94e7-7408448e64a2">
Any idea whats going on?

When I run

```bash
python3 001-rescuetime-activities.1m.py
```

I get pretty benign output:

```bash
0m | color=None
---
RescueTime Activites | href=https://www.rescuetime.com/dashboard
Productive:      0m | font='Menlo' size=12 color=#27ae60
Neutral:         0m | font='Menlo' size=12 color=#3498db
Distracting:     0m | font='Menlo' size=12 color=#e74c3c
---
Top activities
---
Productivity by hour
---
To see daily chart install Pillow
-- most likely you need to run:
-- /usr/local/opt/python@3.12/bin/python3.12 -m pip install Pillow
Then xbar > Refresh (or ⌘+R)
---
Notes
-- RescueTime data syncs every 3 min (Premium) or 30 min (Free)
-- Activities shown are from the last 24 hours
-- Colors indicate productivity level
-- By Piotr Migdał (2024) | href=https://p.migdal.pl
-- Source code available | href=https://github.com/stared/xbar-rescuetime-activities
-- System info
-- Python path: /usr/local/opt/python@3.12/bin/python3.12
-- Python version: 3.12.5
```

**Comment by stared** [comment]
This means that the RescueTime API call returns nothing, e.g:

* wrong API key
* no data logged on a given day

It is supposed to work as an Xbar plugin. 
If you run from the terminal, you must set the env variable `VAR_RESCUETIME_API_KEY` to your API key.

So:

* double-check if the key is correct.
* go to [RescueTimehttps://www.rescuetime.com/dashboard/] to see if it has any logged data.

Let me know if it helps.

**Comment by dtransposed** [comment]
Hey Piotr, thanks. Just regenerated the API key and I got a new error :)

```bash
color: invalid named color "none"
```

Quickly patched it by changing the `print_header` func:

```python
def print_header(productive_seconds: int, pulse: dict) -> None:
    """
    Print the header with productive time and pulse color.

    :param productive_seconds: Total productive seconds.
    :param pulse: Pulse data from RescueTime API.
    :returns: None
    """
    color = pulse.get('color', '#000000')
    if color is None:
        color = '#000000'
    print(f"{format_time(productive_seconds)} | color={color}")
    print("---")
    print("RescueTime Activities | href=https://www.rescuetime.com/dashboard")
```

Now waiting for first logs to be sent my way:
<img width="247" alt="image" src="https://github.com/user-attachments/assets/df9e232f-92f7-4d0d-a400-00f5e079481c">

**Comment by stared** [comment]
As you may have seen, I already changed that in the repo https://github.com/stared/xbar-rescuetime-activities/commit/17120b5bd2391b9d5686717657ef58b6f48a6bf1.

Again, what is your RescueTime dashboard? This plugin does not send any data; it just uses the ResueTime API to present it in the menu bar.

**Comment by dtransposed** [comment]
<img width="269" alt="image" src="https://github.com/user-attachments/assets/fe912927-d33b-494b-a5de-fb8db511e109">
Had to refresh. All good, thanks for the implementation and help!

**Comment by stared** [comment]
@dtransposed happy to hear that.

Have a nice day!
